apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  ingressRef:
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    name: podinfo
  service:
    port: 80
    targetPort: 9898
  progressDeadlineSeconds: 60
  analysis:
    interval: 10s
    threshold: 2
    ## blue-green
    ## https://docs.flagger.app/tutorials/kubernetes-blue-green
    # iterations: 3
    ## canary
    ## https://docs.flagger.app/tutorials/nginx-progressive-delivery
    maxWeight: 50
    stepWeight: 5
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
